config/routes.rb
Rails.application.routes.draw do
  # get 'enrollments/index'
  post 'users/new2' => 'users#create_student'
  get 'users/new2' => 'users#new2'
  post 'users/new' => 'users#create'
  get 'courses/new2' => 'courses#new2'
  resources :users, except: :show
  post 'enrollments/new' => 'enrollments#create'
  resources :enrollments
  get 'sessions/new'
  get 'session/new'
  get 'home/index'
  resources :courses do
    member do
      get :select
      get :quit
      get :open
      get :close
    end
    collection do
      get :list
    end
  end
  root 'home#index'
  get 'sessions/login' => 'sessions#new'
  post 'sessions/login' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :teacher_logged_in

  def index
    @course = Course.find(params[:course_id])
    if teacher_logged_in?
      if @course.teacher_id != current_user.id
        redirect_to root_path, notice: 'You are not authorized to access this page.'
        return
      end
    end
    @enrollments = @course.enrollments.paginate(page: params[:page], per_page: 4)
  end

  def destroy
    @enrollment = Enrollment.find(params[:id])
    @course = @enrollment.course
    if teacher_logged_in?
      if @course.teacher_id != current_user.id
        redirect_to root_path, notice: 'You are not authorized to access this page.'
        return
      end
    end
    @enrollment.destroy
    @course.student_num -= 1
    if @course.status == "CLOSED"
      @course.status = "OPEN"
    end
    @course.save
    flash[:success] = "Enrollment deleted"
    redirect_to enrollments_path(course_id: @course.id)
  end

  def new
    @course = Course.find(params[:course_id])
    if teacher_logged_in?
      if @course.teacher_id != current_user.id
        redirect_to root_path, notice: 'You are not authorized.'
        return
      end
    end
    @users = User.where(:admin => false).where(:teacher => false).where.not(:id => @course.users.pluck(:id)).paginate(page: params[:page], per_page: 10)

  end

  def create
    @course = Course.find(params[:course_id])
    if teacher_logged_in?
      if @course.teacher_id != current_user.id
        redirect_to root_path, notice: 'You are not authorized.'
      end
    end
    if @course.status == "CLOSED"
      redirect_to enrollments_path(course_id: @course.id), flash: { :warning => "Course is closed" }
    else
      @user = User.find(params[:user_id])
      @enrollment = @course.enrollments.build(:user_id => @user.id)
      if @enrollment.save
        @course.student_num += 1
        if @course.student_num == @course.capacity
          @course.status = "CLOSED"
        end
        @course.save
        flash[:success] = "Enrollment created"
        redirect_to enrollments_path(course_id: @course.id)
      else
        render 'new'
      end
    end

  end

  private

  def teacher_logged_in
    unless teacher_logged_in? || admin_logged_in?
      redirect_to root_url, flash: { danger: 'Please login first' }
    end
  end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/index.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
      <%= render "shared/sidenav" %>

    </div>
    <div class="col-sm-10">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <% if teacher_logged_in? %><h3 class="panel-title">Enrollment Management: <%=@course.name%></h3><% end %>
          <% if admin_logged_in? %><h3 class="panel-title"> Admin Enrollment Management: <%=@course.name%></h3><% end %>
        </div>
        <div class="panel-body" style="min-height: 450px">





          <table class="table table-striped table-hover">
            <thead>

            <tr>
              <th>Name</th>
              <th>ID</th>
              <th>Email</th>
              <th>Date of Birth</th>
              <th>Phone number</th>
              <th>Major</th>

            </tr>
            </thead>
            <tbody>

            <% @enrollments.each do |grade| %>
              <tr>
                <td><%= grade.user.name %></td>
                <td><%= grade.user.id %></td>
                <td><%= grade.user.email %></td>
                <td><%= grade.user.birthday %></td>
                <td><%= grade.user.phone_number %></td>
                <td><%= grade.user.major %></td>

                <% if teacher_logged_in? %>
                  <td> <%= link_to "Delete", enrollment_path(grade), method: :delete, data: { confirm: "Are you sure?" } %> </td>
                  <% end %>
                <% if admin_logged_in? %>
                  <td> <%= link_to "Delete", enrollment_path(grade), method: :delete, data: { confirm: "Are you sure?" } %> </td>
                <% end %>
                <% end %>

              </tr>
            <%# end %>
            </tbody>
          </table>

          <%= will_paginate @enrollments %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/enrollments/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-sm-2">
      <%= render "shared/sidenav" %>

    </div>
    <div class="col-sm-10">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <% if teacher_logged_in? %><h3 class="panel-title">Enrollment Management: <%=@course.name%></h3><% end %>
          <% if admin_logged_in? %><h3 class="panel-title">Enrollment Management: <%=@course.name%></h3><% end %>

        </div>
        <div class="panel-body" style="min-height: 450px">
          <table class="table table-striped table-hover">
            <thead>

            <tr>
              <th>Name</th>
              <th>ID</th>
              <th>Email</th>
              <th>Date of Birth</th>
              <th>Phone number</th>
              <th>Major</th>

            </tr>
            </thead>
            <tbody>

            <% @users.each do |user| %>
              <tr>
                <td><%= user.name %></td>
                <td><%= user.id %></td>
                <td><%= user.email %></td>
                <td><%= user.birthday %></td>
                <td><%= user.phone_number %></td>
                <td><%= user.major %></td>

                <% if teacher_logged_in? %>
                  <td> <%= link_to "Add", new_enrollment_path(:user_id => user.id, :course_id => @course.id), method: :post, data: { confirm: "Are you sure?" } %> </td>
                <% end %>
                <% if admin_logged_in? %>
                  <td> <%= link_to "Add", new_enrollment_path(:user_id => user.id, :course_id => @course.id), method: :post, data: { confirm: "Are you sure?" } %> </td>
                <% end %>
            <% end %>

            </tr>
            <%# end %>
            </tbody>
          </table>
          <%= will_paginate @users %>
        </div>
      </div>
    </div>
  </div>
</div>