config/routes.rb
Rails.application.routes.draw do
  # get 'enrollments/index'
  post 'users/new2' => 'users#create_student'
  get 'users/new2' => 'users#new2'
  post 'users/new' => 'users#create'
  get 'courses/new2' => 'courses#new2'
  resources :users, except: :show
  post 'enrollments/new' => 'enrollments#create'
  resources :enrollments
  get 'sessions/new'
  get 'session/new'
  get 'home/index'
  resources :courses do
    member do
      get :select
      get :quit
      get :open
      get :close
    end
    collection do
      get :list
    end
  end
  root 'home#index'
  get 'sessions/login' => 'sessions#new'
  post 'sessions/login' => 'sessions#create'
  delete 'sessions/logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_content.html.erb
<br>
<br>
<br>
<div class="container">
  <% flash.each do |message_type, message| %>
    <div class="alert alert-<%= message_type %>">
      <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
      <strong> <%= message %></strong>
    </div>
  <% end %>
</div>

<%= yield %>

app/views/layouts/_footer.html.erb
<div class="navbar navbar-fixed-bottom">
  <footer class="container-fluid">
    <p class="text-center">N/A
    </p>
  </footer>
</div>

app/views/layouts/_header.html.erb
<!--<script src="http://code.jquery.com/jquery-1.11.0.min.js"></script>-->
<!--<script src="http://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>-->

<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">

    <div class="navbar-header">
      <%= link_to "CourseSelect", root_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">

        <li class=<%= "active" if params[:controller] == "homes" %>> <%= link_to "Homepage", root_path %></li>

        <% if student_logged_in? %>
          <li class=<%= "active" if params[:controller] == "courses" %>> <%= link_to "My Courses", courses_path %></li>
        <% elsif teacher_logged_in? %>
          <li class=<%= "active" if params[:controller] == "courses" %>> <%= link_to "Courses Management", courses_path %></li>
        <% elsif admin_logged_in? %>
          <li class=<%= "active" if params[:controller] == "courses" %>> <%= link_to "Admin Management", courses_path %></li>
        <% end %>

      </ul>

      <ul class="nav navbar-nav navbar-right">

        <% if current_user %>
          <li>
            <%= link_to edit_user_path(current_user) do %>
              <%= current_user.name %><span class="glyphicon glyphicon-user"></span>
            <% end %>
          </li>

          <li>
            <% if admin_logged_in? %>
              <%= link_to edit_user_path(current_user) do %>
                Role: <u> Admin </u><span class="glyphicon glyphicon-user"></span>
              <% end %>
            <% end %>
            <% if student_logged_in? %>
              <%= link_to edit_user_path(current_user) do %>
                Role: <b> Student </b><span class="glyphicon glyphicon-user"></span>
              <% end %>
            <% end %>
            <% if teacher_logged_in? %>
              <%= link_to edit_user_path(current_user) do %>
                Role: <b><i> Instructor </i></b><span class="glyphicon glyphicon-user"></span>
              <% end %>
            <% end %>
          </li>

          <li>
            <%= link_to sessions_logout_path, method: :delete do %>
              Log out <span class="	glyphicon glyphicon-off"></span>
            <% end %>
          </li>

          <% if admin_logged_in? %>
            <li><%= link_to new_user_path do %>
                Create Instructor <span class="	glyphicon glyphicon-log-in"></span>
              <% end %>
            </li>

            <li><%= link_to users_new2_path do %>
                Create Student <span class="	glyphicon glyphicon-log-in"></span>
              <% end %>
          <% end %>

        <% else %>

          <li><%= link_to sessions_login_path do %>
              Log in <span class="	glyphicon glyphicon-user"></span>
            <% end %>
          </li>

          <li><%= link_to new_user_path do %>
              Sign up as Instructor <span class="	glyphicon glyphicon-log-in"></span>
            <% end %>
          </li>

          <li><%= link_to users_new2_path do %>
              Sign up as Student <span class="	glyphicon glyphicon-log-in"></span>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%#= yield %>
    <%= render partial: 'layouts/header' %>
    <%= render partial: 'layouts/content' %>
  </body>
</html>